# Ruff configuration for the Hound submodule

# Global settings
line-length = 120
target-version = "py310"

# Only lint Python files under this directory
include = ["**/*.py", "**/*.pyi"]

exclude = [
  ".git",
  ".venv",
  "venv",
  "__pycache__",
  # Static web assets
  "chatbot/static",
  # Build artifacts or caches (if any)
  ".hound_debug",
]

[lint]
# Rule sets: Flake8 (E), Pyflakes (F), isort (I), pyupgrade (UP)
select = ["E", "F", "I", "UP"]

# Initial ignores to reduce noise on adoption
ignore = [
  "E501",  # line length
  "E203",  # whitespace before ':' (black compatibility)
]

[lint.isort]
known-first-party = ["hound"]
combine-as-imports = true

